# Generated by Django 3.0.4 on 2020-05-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrap',
            old_name='archivement_html',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='game',
            name='wiki_url',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='table_html',
        ),
    ]
