# Generated by Django 3.0.4 on 2020-05-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200522_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
